### PR TITLE
Make health checks runnable locally

### LINKED ISSUE #379: [infra] Migrate some health checks to tool/ci.dart
Currently the health checks are github actions this leads to the following downsides:

1. it's hard to reproduce failures locally (you have to reverse engineer the github action and invoked packages)
2. you cannot run the same checks locally as a sanity check before submitting a PR (this is especially painful for external contributors for which CI-runs need to be approved)'
3. the versions of the tools is not pinned by the dev dependencies in your packages leading to non-hermetic builds.

However, writing code manually per repo will likely lead to code duplication. So may we should provide a Dart API for the health checks that users can add as a dev dependency. WDYT @mosuem?

### PR DESCRIPTION
**Pull request by mosuem**
Fixes #379, or at least tries to go there. Still plenty of room for improvement, but a good start.

TODOs for future PRs: 
- The list of files should be obtained by diffing the current git branch to the main branch instead of using all files as done right now.
- The user should be allowed to specify more output formats.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.

**Note**: The Dart team is trialing Gemini Code Assist. Don't take its comments as final Dart team feedback. Use the suggestions if they're helpful; otherwise, wait for a human reviewer.

</details>

### CODE REVIEW

File: pkgs/firehose/bin/health.dart [hunk 1]
```diff
@@ -91,22 +99,39 @@ void main(List<String> arguments) async {
...
+  if (isLocal) {
+    final files = Directory.current
+        .listSync(recursive: true)
+        .whereType<File>()
+        .map(
+          (e) => GitFile(p.relative(e.path, from: Directory.current.path),
+              FileStatus.added, Directory.current),
+        )
+        .toList();
+    githubApi = LocalGithubApi(prLabels: [], files: files);
```
Comment (mosuem) [inline pkgs/firehose/bin/health.dart]: In the future, we can add more configurability to this.

File: pkgs/firehose/lib/src/health/health.dart [hunk 2]
```diff
@@ -258,42 +259,55 @@ For details on how to fix these, see [dependency_validator](https://pub.dev/pack
...
+        changeForPackage[package] = BreakingChange(
+          level: _breakingLevel(report),
+          oldVersion: Version.parse(versionMap['old'].toString()),
+          newVersion: Version.parse(versionMap['new'].toString()),
+          neededVersion: Version.parse(versionMap['needed'].toString()),
+          versionIsFine: versionMap['success'] as bool,
+          explanation: versionMap['explanation'].toString(),
+        );
+      } else {
+        log('Report was not created for $package at $reportPath');
```
Comment (mosuem) [inline pkgs/firehose/lib/src/health/health.dart]: Just to make sure that errors are nicely surfaced.
